# duoshuo comment
duoshuo: false
duoshuo_name:

# google analytics
googleTrackId:

# disqus
disqus: true
disqus_shortname: billplaygroundtest

# menu
menu:
  Home: /
  Archives: /archives
  测试服务器: https://test.billzhonggz.com